name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build full version
      run: |
        pyinstaller -w -F `
          --add-data '.\\icon.ico;.' `
          --add-data '.\\bin\\*;.\\bin' `
          -i '.\\icon.ico' record.py
        move dist\record.exe dist\record-$env:VERSION-full.exe

    - name: Build minimal version
      run: |
        pyinstaller -w -F `
          --add-data '.\\icon.ico;.' `
          -i '.\\icon.ico' record.py
        move dist\record.exe dist\record-$env:VERSION.exe

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/record-${{ env.VERSION }}.exe
          dist/record-${{ env.VERSION }}-full.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
